export const familyDetails = [
  {
    husbandName: "Durgesh Tripathi",
    wifeName: "Madhu Tripathi",
    husbandPhoneNumber: "9191919191",
    wifePhoneNumber: "9916046415",
    city: "Lucknow",
    husbandDetails: {
      title: "Mr",
      first: "Durgesh",
      last: "Tripathi",
      picture: "https://randomuser.me/api/portraits/men/72.jpg",
      dateOfBirth: "1 Aug 1988",
      phoneNumber: "9191919191",
      anniversaryDate: "21 Dec 1982",
      email: "tripathi.ror@gmail.com",
      homeAddress: "#18, Safdar Ganj, Lucknow",
      workAddress: "#20, Safdar Ganj, Lucknow",
      occupation: "Software Engineer",
    },
    wifeDetails: {
      title: "Mrs",
      first: "Madhu",
      last: "Tripathi",
      picture: "https://randomuser.me/api/portraits/women/50.jpg",
      dateOfBirth: "06 Sep 1992",
      phoneNumber: "9191919191",
      anniversaryDate: "21 Dec 1982",
      email: "madhu.tripathi@gmail.com",
      homeAddress: "#18, Safdar Ganj, Lucknow",
      workAddress: "#20, Safdar Ganj, Lucknow",
      occupation: "Software Engineer",
    },
  },
  {
    husbandName: "Girjesh Tripathi",
    wifeName: "Divya Tripathi",
    husbandPhoneNumber: "9899915942",
    wifePhoneNumber: "9178110911",
    city: "Bangalore",
    husbandDetails: {
      title: "Mr",
      first: "Girjesh",
      last: "Tripathi",
      picture: "https://randomuser.me/api/portraits/men/76.jpg",
      dateOfBirth: "1 Aug 1988",
      phoneNumber: "9191919191",
      anniversaryDate: "21 Dec 1982",
      email: "tripathi.ror@gmail.com",
      homeAddress: "#18, Safdar Ganj, Bangalore",
      workAddress: "#20, Safdar Ganj, Bangalore",
      occupation: "Software Engineer",
    },
    wifeDetails: {
      title: "Mrs",
      first: "Divya",
      last: "Tripathi",
      picture: "https://randomuser.me/api/portraits/women/67.jpg",
      dateOfBirth: "06 Sep 1992",
      phoneNumber: "9191919191",
      anniversaryDate: "21 Dec 1982",
      email: "madhu.tripathi@gmail.com",
      homeAddress: "#18, Safdar Ganj, Bangalore",
      workAddress: "#20, Safdar Ganj, Bangalore",
      occupation: "Software Engineer",
    },
  },
  {
    husbandName: "Saurabh Mohta",
    wifeName: "Vrinda Mohta",
    husbandPhoneNumber: "8881234511",
    wifePhoneNumber: "9118910911",
    city: "Hyderabad",
    husbandDetails: {
      title: "Mr",
      first: "Saurabh",
      last: "Mohta",
      picture: "https://randomuser.me/api/portraits/men/32.jpg",
      dateOfBirth: "1 Aug 1988",
      phoneNumber: "9191919191",
      anniversaryDate: "21 Dec 1982",
      email: "saurabh.mohta@gmail.com",
      homeAddress: "#18, Safdar Ganj, Hyderabad",
      workAddress: "#20, Safdar Ganj, Hyderabad",
      occupation: "Software Engineer",
    },
    wifeDetails: {
      title: "Mrs",
      first: "Vrinda",
      last: "Mohta",
      picture: "https://randomuser.me/api/portraits/women/2.jpg",
      dateOfBirth: "06 Sep 1992",
      phoneNumber: "9191919191",
      anniversaryDate: "21 Dec 1982",
      email: "vrinda.mohta@gmail.com",
      homeAddress: "#18, Safdar Ganj, Hyderabad",
      workAddress: "#20, Safdar Ganj, Hyderabad",
      occupation: "Software Engineer",
    },
  },
  {
    husbandName: "Mukul Mohta",
    wifeName: "Mona Mohta",
    husbandPhoneNumber: "7881234511",
    wifePhoneNumber: "9008910911",
    city: "Hyderabad",
    husbandDetails: {
      title: "Mr",
      first: "Mukul",
      last: "Mohta",
      picture: "https://randomuser.me/api/portraits/men/98.jpg",
      dateOfBirth: "1 Aug 1988",
      phoneNumber: "7881234511",
      anniversaryDate: "21 Dec 1982",
      email: "mukul.mohta@gmail.com",
      homeAddress: "#18, Safdar Ganj, Hyderabad",
      workAddress: "#20, Safdar Ganj, Hyderabad",
      occupation: "Software Engineer",
    },
    wifeDetails: {
      title: "Mrs",
      first: "Mona",
      last: "Mohta",
      picture: "https://randomuser.me/api/portraits/women/32.jpg",
      dateOfBirth: "06 Sep 1992",
      phoneNumber: "9191919191",
      anniversaryDate: "21 Dec 1982",
      email: "mona.mohta@gmail.com",
      homeAddress: "#18, Safdar Ganj, Hyderabad",
      workAddress: "#20, Safdar Ganj, Hyderabad",
      occupation: "Software Engineer",
    },
  },
  {
    husbandName: "Rustom Sagar",
    wifeName: "Rinki Sagar",
    husbandPhoneNumber: "7881234522",
    wifePhoneNumber: "9008923911",
    city: "Lucknow",
    husbandDetails: {
      title: "Mr",
      first: "Rustom",
      last: "Sagar",
      picture: "https://randomuser.me/api/portraits/men/56.jpg",
      dateOfBirth: "1 Aug 1988",
      phoneNumber: "7881234511",
      anniversaryDate: "21 Dec 1982",
      email: "rustom.sagara@gmail.com",
      homeAddress: "#18, Safdar Ganj, Hyderabad",
      workAddress: "#20, Safdar Ganj, Hyderabad",
      occupation: "Software Engineer",
    },
    wifeDetails: {
      title: "Mrs",
      first: "Rinki",
      last: "Sagar",
      picture: "https://randomuser.me/api/portraits/women/22.jpg",
      dateOfBirth: "06 Sep 1992",
      phoneNumber: "9191919191",
      anniversaryDate: "21 Dec 1982",
      email: "rinki.sagar@gmail.com",
      homeAddress: "#18, Safdar Ganj, Hyderabad",
      workAddress: "#20, Safdar Ganj, Hyderabad",
      occupation: "Software Engineer",
    },
  },
];
